In [29]:
from __future__ import print_function

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop

In [30]:
batch_size = 128
num_classes = 10
epochs = 2

In [49]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [50]:
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

60000 train samples
10000 test samples


In [51]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [53]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [55]:
print(y_train[0])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [35]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [36]:
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(784,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 512)               401920    
_________________________________________________________________
dropout_5 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_6 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_9 (Dense)              (None, 10)                5130      
Total params: 669,706
Trainable params: 669,706
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.compile(loss='categorical_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

In [38]:
history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 5s - loss: 0.2440 - acc: 0.9240 - val_loss: 0.0979 - val_acc: 0.9691
Epoch 2/2
60000/60000 [==============================] - 5s - loss: 0.1030 - acc: 0.9678 - val_loss: 0.0862 - val_acc: 0.9744


In [39]:
score = model.evaluate(x_test, y_test, verbose=0)

In [40]:
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.08622984015108086
Test accuracy: 0.9744


In [41]:
import numpy as np

In [42]:
x=np.array([x_test[0]])

In [43]:
model.predict(x,verbose=1)

1/1 [==============================] - 0s


array([[1.5136786e-09, 1.1888668e-08, 2.1632143e-06, 3.6143327e-05,
        5.8919796e-12, 3.7741864e-07, 3.3933966e-14, 9.9995852e-01,
        2.1395786e-08, 2.7685592e-06]], dtype=float32)

In [44]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])